import React from "react";

function LightFundamentals() {
  const handleClick = (topic) => {
    alert(`You clicked on: ${topic}`);
  };

  return (
    <div className="p-4 bg-gray-100 text-gray-800">
      <h1 className="text-4xl font-bold text-blue-800 mb-6">
        Fundamental Properties of Light
      </h1>

      {/* Section 1 */}
      <section className="mb-8 p-4 bg-white rounded-lg shadow-md">
        <h2 className="text-2xl font-semibold text-gray-700 mb-4 text-left">
          1. What is Light?
        </h2>
        <div className="flex flex-col items-center">
          <p className="text-gray-600 mb-4 text-center">
            Light surrounds us each day, but what exactly is it? A particle? A
            wave? Unfortunately, depending on the property being investigated, the
            answer varies from "one", "both", to "neither" as well as "we're not
            quite sure."
          </p>
          <img
            src="https://pace.oceansciences.org/images/Freq_Wavelength_white_v2.jpg"
            alt="Light Illustration"
            className="max-w-xs rounded-lg mb-4"
          />
          <button
            className="bg-teal-400 hover:bg-teal-500 text-white py-2 px-4 rounded-lg shadow-md transition duration-300"
            onClick={() => handleClick("What is Light?")}
          >
            Learn More
          </button>
        </div>
      </section>

      {/* Section 2 */}
      <section className="mb-8 p-4 bg-white rounded-lg shadow-md">
        <h2 className="text-2xl font-semibold text-gray-700 mb-4 text-left">
          How is Light Categorized?
        </h2>
        <div className="flex flex-col items-center">
          <p className="text-gray-600 mb-4 text-center">
            This spectrum of energy, or spectrum of light, is referred to as the
            Electromagnetic Spectrum. NASA explores the properties of different
            wavelength regions in the electromagnetic spectrum ranging from
            radiowaves to gamma rays.
          </p>
          <img
            src="https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fExpZ2h0JTIwQ2F0ZWdvcml6ZWR8ZW58MHx8MHx8fDA%3D"
            alt="Electromagnetic Spectrum"
            className="max-w-xs rounded-lg mb-4"
          />
          <button
            className="bg-teal-400 hover:bg-teal-500 text-white py-2 px-4 rounded-lg shadow-md transition duration-300"
            onClick={() => handleClick("How is Light Categorized?")}
          >
            Learn More
          </button>
        </div>
      </section>

      {/* Section 3 */}
      <section className="mb-8 p-4 bg-white rounded-lg shadow-md">
        <h2 className="text-2xl font-semibold text-gray-700 mb-4 text-left">
          How Does Light Move or "Behave"?
        </h2>
        <div className="flex flex-col items-center">
          <p className="text-gray-600 mb-4 text-center">
            Most of the light reaching earth comes from our Sun. It is generated by
            nuclear reactions in the Sun's core that convert hydrogen into helium,
            releasing energy (photons!) in the process.
          </p>
          <img
            src="https://pace.oceansciences.org/images/HowDoesLightMoveCompiled_v2.jpg"
            alt="Light Behavior"
            className="max-w-xs rounded-lg mb-4"
          />
          <button
            className="bg-teal-400 hover:bg-teal-500 text-white py-2 px-4 rounded-lg shadow-md transition duration-300"
            onClick={() => handleClick("How Does Light Move?")}
          >
            Learn More
          </button>
        </div>
      </section>

      {/* Section 4 */}
      <section className="mb-8 p-4 bg-white rounded-lg shadow-md">
        <h2 className="text-2xl font-semibold text-gray-700 mb-4 text-left">
          Advanced Topic - Types of Scattering
        </h2>
        <div className="flex flex-col items-center">
          <p className="text-gray-600 mb-4 text-center">
            Scattering occurs when light bounces off an object in a variety of
            directions. The amount of scattering that takes place depends on the
            wavelength of the light and the size and structure of the object.
          </p>
          <img
            src="https://images.unsplash.com/photo-1620642764115-377f63bcfbc4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8U2NhdHRlcmluZ3xlbnwwfHwwfHx8MA%3D%3D"
            alt="Types of Scattering"
            className="max-w-xs rounded-lg mb-4"
          />
          <button
            className="bg-teal-400 hover:bg-teal-500 text-white py-2 px-4 rounded-lg shadow-md transition duration-300"
            onClick={() => handleClick("Types of Scattering")}
          >
            Learn More
          </button>
        </div>
      </section>

      {/* Section 5 */}
      <section className="mb-8 p-4 bg-white rounded-lg shadow-md">
        <h2 className="text-2xl font-semibold text-gray-700 mb-4 text-left">
          How Do Rainbows Work?
        </h2>
        <div className="flex flex-col items-center">
          <p className="text-gray-600 mb-4 text-center">
            Rainbows are multicolor displays created by sunlight shining through
            raindrops. Light rays entering raindrops undergo refraction at the
            initial surface of the raindrop, which bends the light rays and causes a
            separation of the light into the distinct colors of the visible
            spectrum.
          </p>
          <img
            src="https://media.istockphoto.com/id/1469061876/photo/rainbow-at-sunset-beach-oahu-hawaii.webp?a=1&b=1&s=612x612&w=0&k=20&c=dltWC4lKbu8eiiBxfIY3wi0-s7nwQ9x27ksdVa6FyH0="
            alt="Rainbow"
            className="max-w-xs rounded-lg mb-4"
          />
          <button
            className="bg-teal-400 hover:bg-teal-500 text-white py-2 px-4 rounded-lg shadow-md transition duration-300"
            onClick={() => handleClick("How Do Rainbows Work?")}
          >
            Learn More
          </button>
        </div>
      </section>
    </div>
  );
}

export default LightFundamentals;
